name: Org Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - 'org/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  org-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set app version
        run: |
          echo "{\"version\":\"${GITHUB_HEAD_REF##*/}\",\"timestamp\":\"$(date +"%Y-%m-%dT%H:%M:%S%z")\"}" > version.json

      - name: npm install and npm run build
        run: |
          echo "Org: ${GITHUB_REF##*/}"
          echo "Current path: $(pwd)"
          ls -la
          npm ci --ignore-scripts
          npm run build -- -c "${GITHUB_REF#*/*/}"
          cp version.json ./dist/sh-organization-client/

      - name: Printing app version
        run: |
          cat dist/sh-organization-client/version.json | jq

      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: provider.${GITHUB_REF##*/}.pointmotioncontrol.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: /home/runner/work/sh-organization-client/sh-organization-client/dist/sh-organization-client
